
CondaError: Run 'conda init' before 'conda activate'

/eejit/home/hausw001/HybGGM/hybGGM_test/src/model/models.py:425: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_reload.load_state_dict(torch.load(os.path.join(log_dir, 'best_model.pth')))
Traceback (most recent call last):
  File "/eejit/home/hausw001/HybGGM/hybGGM_test/src/model/run_hyperparam_testing_random_areas.py", line 82, in <module>
    models.RS_hyperparam_tuning_prediction(validation_loader, model_type, log_directory, testing_path, device)
  File "/eejit/home/hausw001/HybGGM/hybGGM_test/src/model/models.py", line 425, in RS_hyperparam_tuning_prediction
    model_reload.load_state_dict(torch.load(os.path.join(log_dir, 'best_model.pth')))
  File "/eejit/home/hausw001/.conda/envs/env_hybGGM/lib/python3.10/site-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/eejit/home/hausw001/.conda/envs/env_hybGGM/lib/python3.10/site-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/eejit/home/hausw001/.conda/envs/env_hybGGM/lib/python3.10/site-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'results/testing/random_sampling_180/UNet6_50_0.0001_2_1.0/best_model.pth'
